# Generated by Django 3.1.7 on 2021-04-12 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pyflow', '0005_postlike_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='postshow',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_shows', to=settings.AUTH_USER_MODEL),
        ),
    ]
