# Generated by Django 3.1.7 on 2021-04-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyflow', '0008_auto_20210416_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
